module.exports.userManager = require('./user.manager')
module.exports.tokenManager = require('./token.manager')
module.exports.authManager = require('./auth.manager')
module.exports.profileManager = require('./profile.manager')
module.exports.productManager = require('./product.manager')